# Generated by Django 5.0.2 on 2024-02-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
